### ISSUE TITLE
git aa and git cm

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#10]
We've added an alias for `git acm` to `add -A` and `commit -m`, but sometimes you want to do those operations individually.

Shall we add:

- `aa` => `add -A`
- `cm` => `commit`
- `cm "blah"` => `commit -m "blah"`

?

**Comment by jelaniwoods** [comment]
Added in https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/ae739168b0b54d3c8a463f2187761485f5b89e28
