### ISSUE TITLE
Turn off "format on save" in vscode settings for erb and rb?

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#11]
I don't know if we want to format on save:

- it could be confusing for things to change under their feet.
- it seems to generate error messages more often than not.
- they mostly use autosave anyway.

**Comment by jelaniwoods** [comment]
resolved in https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/a106c4cf2d52893c792ba7f08f1a5458e934646e
