### ISSUE TITLE
Alias "bundle exec" to "be"?

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#12]
One of my most used shortcuts is aliasing "bundle exec " to "be ". Shall we do it in our image?

**Comment by jelaniwoods** [comment]
I've already added this to the `Dockerfile` in https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/6f6093528b0efb1c9cb04765bc8970e021cb03aa.

**Comment by raghubetina** [comment]
Nice, thanks!
