### ISSUE TITLE
redis / cable.yml

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#4]
I notice that the `redis` gem and `config/cable.yml` are not present, even though they are present in a vanilla `rails new` (I think).

Was there a reason for omitting/removing them? Is this based on a vanilla `rails new`, or perhaps something like `rails new --minimal`?

**Comment by jelaniwoods** [comment]
@raghubetina I think I generated this repo with these flags:

```bash
--database=postgresql --skip-action-cable --skip-active-storage --skip-system-test --skip-test --skip-action-mailbox --skip-action-text --skip-action-mailer --skip-javascript
```

Then I re-added JS using importmaps.

> Was there a reason for omitting/removing them? 

🤔 I _feel_ like I had a reason, but I don't remember anymore.

**Comment by jelaniwoods** [comment]
I re-added action-cable, active-storage, action mailer in this commit https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/ae739168b0b54d3c8a463f2187761485f5b89e28. (i don't think there are any additional files/settings to enable action mailbox or action text)

This also made me realize Redis needs to be added, so I did that too.

**Comment by jelaniwoods** [comment]
Closing this, since it's been resolved (both here and in [jelaniwoods-appdev/vanilla-rails-7](https://github.com/jelaniwoods-appdev/vanilla-rails-7))
