### ISSUE TITLE
New terminal tabs display potentially confusing noise about `pyenv`

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#6]
Every time I open a new terminal tab, I see a few lines about `pyenv shell 3.7.6`. Can we eliminate or are they unavoidable?

<img width="930" alt="Screen Shot 2023-01-24 at 10 29 42 AM" src="https://user-images.githubusercontent.com/811217/214350989-c7554021-d1fa-4595-847b-edce8a0bd946.png">

**Comment by jelaniwoods** [comment]
That is annoying. It's not clear to me where the source of that message is right now, but I'll investigate more.

**Comment by jelaniwoods** [comment]
I followed a Gitpod example Dockerfile for installing Python for this image and apparently all of there example Python workspaces do this too. It should be related to `pyenv` but I don't see the setting that actually runs `pyenv shell 3.7.6` when a new terminal is opened. I'll need to install it a different way.

**Comment by jelaniwoods** [comment]
I no longer install `pyenv` which resolves the issue (https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/ae739168b0b54d3c8a463f2187761485f5b89e28). Unsure if `pyenv` will become necessary/useful to have at some point, but even if it does it probably won't be in the Rails focused image.
