### ISSUE TITLE
Minimizing terminal output

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#7]
I like that there is descriptive `print` statements for each of the setup scripts, but I think sometimes it confuses students. For example, when uninstalling extensions, sometimes they think that errors occurred and stop there.

Perhaps we should remove that output after we've ensured that things are working well? Or we could just output a `.` (like passing tests) if things go as expected, and only verbosely output when things go wrong?

**Comment by jelaniwoods** [comment]
I changed to printing `.` if successful and `X (extension first name)` if unsuccessful in https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/ae739168b0b54d3c8a463f2187761485f5b89e28.
