### ISSUE TITLE
git config --global --add --bool push.autoSetupRemote true

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods-appdev/appdev-rails-7#9]
To avoid having to set upstream branch on first push, https://stackoverflow.com/a/72994973

**Comment by jelaniwoods** [comment]
I think if we add this setting, it should be clear in the Git chapter that this is non-default behavior, in case students work locally and they see a message they've never seen before.

**Comment by raghubetina** [comment]
> I think if we add this setting, it should be clear in the Git chapter that this is non-default behavior, in case students work locally and they see a message they've never seen before.

Sounds good to me. Although if they're working locally, it sort of implies that they're at the stage where they can read the output of the failed command (which describes this setting), no?

**Comment by jelaniwoods** [comment]
> Although if they're working locally, it sort of implies that they're at the stage where they can read the output of the failed command (which describes this setting), no?

I think they _should_ definitely be able to read and understand the output in that particular case if they're working locally. Based on some of the questions I've had in office hours, I'm not positive that everyone would feel confident that running the command wouldn't break anything.

**Comment by jelaniwoods** [comment]
Added in https://github.com/jelaniwoods-appdev/appdev-rails-7/commit/ae739168b0b54d3c8a463f2187761485f5b89e28
